name: Package Deployment Template
on:
  workflow_call:
    inputs:
      packageName:
        required: false
        default: ''
        type: string
      projectPath:
        required: false
        default: ''
        type: string      

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.4

    - name: Add Package Source
      run: |-
        dotnet nuget add source https://nuget.pkg.github.com/astro-panda/index.json --name github --username "${{ github.repository_owner }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text 

    - name: Restore ${{ inputs.packageName }}
      run: |-
        dotnet build ${{ inputs.projectPath }}

    - name: Test ${{ inputs.packageName }}
      run: |-
        dotnet test ${{ inputs.projectPath }} --logger trx --results-directory "${{ runner.temp }}"    

    - name: Pack ${{ inputs.packageName }}
      if: (github.ref_name == 'main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
      run: |-
        dotnet pack ${{ inputs.projectPath }} --output "${{ runner.temp }}"   
    
    - name: Publish ${{ inputs.packageName }}
      if: (github.ref_name == 'main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
      run: |-        
        dotnet nuget push "**/*.nupkg" -s github
